#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#define HAL_GPRS_POWER_PIN 0x00
#define HAL_GPRS_POWER_ACTIVE_LEVEL   0
#define HAL_GPRS_POWER_DEACTIVE_LEVEL 1

#define HAL_GPRS_SLEEP_PIN 0x01

#define HAL_STATUS_LED_PIN 0x24
#define HAL_STATUS_LED_ENABLE_LEVEL  0
#define HAL_STATUS_LED_DISABLE_LEVEL 1

#define HAL_GPRS_RECV_QUEUE_LEN  512

#define KB(x) ((x)*1024)
/*flash分区
* 0 ~ 5k     :boot
* 5k ~ 125k  :app
* 125k ~ 245k:ota
* 245k ~ 256k:args
*/
#define HAL_FLASH_SIZE (KB(256))  //256KB 120k(ota), 4k(boot) 4+240+12
#define HAL_FLASH_PAGE_SIZE (KB(2))
#define HAL_FLASH_OTA_SIZE (KB(120))

#define HAL_FLASH_BASE_ADDR  0x8000000
#define HAL_BOOT_FLASH_ADDR  (HAL_FLASH_BASE_ADDR + 0)
#define HAL_APP_FLASH_ADDR   (HAL_FLASH_BASE_ADDR + KB(4))
#define HAL_OTA_FLASH_ADDR   (HAL_FLASH_BASE_ADDR + KB(124))
#define HAL_ARGS_FLASH_ADDR  (HAL_FLASH_BASE_ADDR + KB(244))

#define HAL_DEVICE_ID_FLASH_ADDR (HAL_ARGS_FLASH_ADDR + 0) //设备ID和pwd
#define HAL_DEVICE_SYS_ARGS_ADDR (HAL_ARGS_FLASH_ADDR + KB(2))
#define HAL_DEVICE_OTA_INFO_ADDR (HAL_ARGS_FLASH_ADDR + KB(4))

#endif

